name: planternativo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.3
  permission_handler: ^9.2.0

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  firebase_core:
  equatable:
  flutter_shimmer:
  # Firebase
  firebase_auth:
  google_sign_in:
  cloud_firestore:
  flutterfire_ui:
  firebase_storage:
  image_picker:
  flutter_signin_button: ^2.0.0
  google_fonts: ^2.3.1
  location: ^4.3.0
  location_web: ^3.1.1
  geolocator: ^8.2.0
  geolocator_web: ^2.1.4
  flutter_phone_direct_caller: ^2.1.1
  flutter_rating_bar: ^4.0.0
  screenshot: ^1.2.3
  share_plus: ^4.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/vegan-vegan-power.gif
    - assets/menu/
